package nl.basvanmarwijk.mylocations.db.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import nl.basvanmarwijk.mylocations.db.dao.Location_picture;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table LOCATION_PICTURE.
*/
public class Location_pictureDao extends AbstractDao<Location_picture, Long> {

    public static final String TABLENAME = "LOCATION_PICTURE";

    /**
     * Properties of entity Location_picture.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Picture_path = new Property(1, String.class, "picture_path", false, "PICTURE_PATH");
        public final static Property Location_id = new Property(2, long.class, "location_id", false, "LOCATION_ID");
    };

    private Query<Location_picture> location_Fk_location_pictureQuery;

    public Location_pictureDao(DaoConfig config) {
        super(config);
    }
    
    public Location_pictureDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'LOCATION_PICTURE' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'PICTURE_PATH' TEXT NOT NULL UNIQUE ," + // 1: picture_path
                "'LOCATION_ID' INTEGER NOT NULL );"); // 2: location_id
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'LOCATION_PICTURE'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Location_picture entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getPicture_path());
        stmt.bindLong(3, entity.getLocation_id());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Location_picture readEntity(Cursor cursor, int offset) {
        Location_picture entity = new Location_picture( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // picture_path
            cursor.getLong(offset + 2) // location_id
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Location_picture entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPicture_path(cursor.getString(offset + 1));
        entity.setLocation_id(cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Location_picture entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Location_picture entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "fk_location_picture" to-many relationship of Location. */
    public List<Location_picture> _queryLocation_Fk_location_picture(long location_id) {
        synchronized (this) {
            if (location_Fk_location_pictureQuery == null) {
                QueryBuilder<Location_picture> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Location_id.eq(null));
                location_Fk_location_pictureQuery = queryBuilder.build();
            }
        }
        Query<Location_picture> query = location_Fk_location_pictureQuery.forCurrentThread();
        query.setParameter(0, location_id);
        return query.list();
    }

}
