package nl.basvanmarwijk.mylocations.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATION_TIME.
 */
public class Location_time {

    private long datetimestamp;
    private long location_id;

    public Location_time() {
    }

    public Location_time(long datetimestamp) {
        this.datetimestamp = datetimestamp;
    }

    public Location_time(long datetimestamp, long location_id) {
        this.datetimestamp = datetimestamp;
        this.location_id = location_id;
    }

    public long getDatetimestamp() {
        return datetimestamp;
    }

    public void setDatetimestamp(long datetimestamp) {
        this.datetimestamp = datetimestamp;
    }

    public long getLocation_id() {
        return location_id;
    }

    public void setLocation_id(long location_id) {
        this.location_id = location_id;
    }

}
