package nl.basvanmarwijk.mylocations.db.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LOCATION_PICTURE.
 */
public class Location_picture {

    private Long id;
    /** Not-null value. */
    private String picture_path;
    private long location_id;

    public Location_picture() {
    }

    public Location_picture(Long id) {
        this.id = id;
    }

    public Location_picture(Long id, String picture_path, long location_id) {
        this.id = id;
        this.picture_path = picture_path;
        this.location_id = location_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getPicture_path() {
        return picture_path;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPicture_path(String picture_path) {
        this.picture_path = picture_path;
    }

    public long getLocation_id() {
        return location_id;
    }

    public void setLocation_id(long location_id) {
        this.location_id = location_id;
    }

}
